/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SwapCreateNestedManyWithoutUsersInput } from "./SwapCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { PoolCreateNestedManyWithoutUsersInput } from "./PoolCreateNestedManyWithoutUsersInput";
import { PairCreateNestedManyWithoutUsersInput } from "./PairCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  walletAddress?: string | null;

  @ApiProperty({
    required: false,
    type: () => SwapCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SwapCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SwapCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  swaps?: SwapCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => PoolCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PoolCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PoolCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  pools?: PoolCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => PairCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PairCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PairCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  pairs?: PairCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
