/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SwapListRelationFilter } from "../../swap/base/SwapListRelationFilter";
import { PoolListRelationFilter } from "../../pool/base/PoolListRelationFilter";
import { PairListRelationFilter } from "../../pair/base/PairListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  userName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  walletAddress?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SwapListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SwapListRelationFilter)
  @IsOptional()
  @Field(() => SwapListRelationFilter, {
    nullable: true,
  })
  swaps?: SwapListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PoolListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PoolListRelationFilter)
  @IsOptional()
  @Field(() => PoolListRelationFilter, {
    nullable: true,
  })
  pools?: PoolListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PairListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PairListRelationFilter)
  @IsOptional()
  @Field(() => PairListRelationFilter, {
    nullable: true,
  })
  pairs?: PairListRelationFilter;
}

export { UserWhereInput as UserWhereInput };
