/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SwapUpdateManyWithoutUsersInput } from "./SwapUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { PoolUpdateManyWithoutUsersInput } from "./PoolUpdateManyWithoutUsersInput";
import { PairUpdateManyWithoutUsersInput } from "./PairUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  walletAddress?: string | null;

  @ApiProperty({
    required: false,
    type: () => SwapUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SwapUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SwapUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  swaps?: SwapUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => PoolUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PoolUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PoolUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  pools?: PoolUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => PairUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PairUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PairUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  pairs?: PairUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
