/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Pool } from "./Pool";
import { PoolCountArgs } from "./PoolCountArgs";
import { PoolFindManyArgs } from "./PoolFindManyArgs";
import { PoolFindUniqueArgs } from "./PoolFindUniqueArgs";
import { CreatePoolArgs } from "./CreatePoolArgs";
import { UpdatePoolArgs } from "./UpdatePoolArgs";
import { DeletePoolArgs } from "./DeletePoolArgs";
import { User } from "../../user/base/User";
import { PoolService } from "../pool.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Pool)
export class PoolResolverBase {
  constructor(
    protected readonly service: PoolService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pool",
    action: "read",
    possession: "any",
  })
  async _poolsMeta(
    @graphql.Args() args: PoolCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Pool])
  @nestAccessControl.UseRoles({
    resource: "Pool",
    action: "read",
    possession: "any",
  })
  async pools(@graphql.Args() args: PoolFindManyArgs): Promise<Pool[]> {
    return this.service.pools(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Pool, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pool",
    action: "read",
    possession: "own",
  })
  async pool(@graphql.Args() args: PoolFindUniqueArgs): Promise<Pool | null> {
    const result = await this.service.pool(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pool)
  @nestAccessControl.UseRoles({
    resource: "Pool",
    action: "create",
    possession: "any",
  })
  async createPool(@graphql.Args() args: CreatePoolArgs): Promise<Pool> {
    return await this.service.createPool({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pool)
  @nestAccessControl.UseRoles({
    resource: "Pool",
    action: "update",
    possession: "any",
  })
  async updatePool(@graphql.Args() args: UpdatePoolArgs): Promise<Pool | null> {
    try {
      return await this.service.updatePool({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pool)
  @nestAccessControl.UseRoles({
    resource: "Pool",
    action: "delete",
    possession: "any",
  })
  async deletePool(@graphql.Args() args: DeletePoolArgs): Promise<Pool | null> {
    try {
      return await this.service.deletePool(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Pool): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
