/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SwapService } from "../swap.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SwapCreateInput } from "./SwapCreateInput";
import { Swap } from "./Swap";
import { SwapFindManyArgs } from "./SwapFindManyArgs";
import { SwapWhereUniqueInput } from "./SwapWhereUniqueInput";
import { SwapUpdateInput } from "./SwapUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SwapControllerBase {
  constructor(
    protected readonly service: SwapService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Swap })
  @nestAccessControl.UseRoles({
    resource: "Swap",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSwap(@common.Body() data: SwapCreateInput): Promise<Swap> {
    return await this.service.createSwap({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tokenB: true,
        tokenA: true,
        amountA: true,
        amountB: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Swap] })
  @ApiNestedQuery(SwapFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Swap",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async swaps(@common.Req() request: Request): Promise<Swap[]> {
    const args = plainToClass(SwapFindManyArgs, request.query);
    return this.service.swaps({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tokenB: true,
        tokenA: true,
        amountA: true,
        amountB: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Swap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Swap",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async swap(
    @common.Param() params: SwapWhereUniqueInput
  ): Promise<Swap | null> {
    const result = await this.service.swap({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tokenB: true,
        tokenA: true,
        amountA: true,
        amountB: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Swap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Swap",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSwap(
    @common.Param() params: SwapWhereUniqueInput,
    @common.Body() data: SwapUpdateInput
  ): Promise<Swap | null> {
    try {
      return await this.service.updateSwap({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tokenB: true,
          tokenA: true,
          amountA: true,
          amountB: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Swap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Swap",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSwap(
    @common.Param() params: SwapWhereUniqueInput
  ): Promise<Swap | null> {
    try {
      return await this.service.deleteSwap({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tokenB: true,
          tokenA: true,
          amountA: true,
          amountB: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
